api_list_cars:
  path: /api/v1/cars
  controller: App\Layer\Presentation\Controller\Car\CarController::listAll
  methods: [GET]

api_list_car_by_id:
  path: /api/v1/cars/{id}
  controller: App\Layer\Presentation\Controller\Car\CarController::listById
  methods: [GET]
  requirements:
    id: '\d+'

api_calculate_credit:
  path: /api/v1/credit/calculate?carId={carId}&initialPayment={initialPayment}&loanTerm={loanTerm}
  controller: App\Layer\Presentation\Controller\Credit\CreditController::calculate
  methods: [GET]
  requirements:
    carId: '\d+'
    initialPayment: '\d+'
    loanTerm: '\d+'

api_save_credit_request:
  path: /api/v1/request
  controller: App\Layer\Presentation\Controller\Credit\CreditController::save
  methods: [POST]
  requirements:
    carId: '\d+'
    programId: '\d+'
    initialPayment: '\d+'
    loanTerm: '\d+'